---
- hosts: webservers
  become: yes
  vars:
    debug:
    - msg: "Welcome to webservers"
  
  tasks:
    - name: Ensure  Nginx Install  
      apt: name=nginx state=latest update_cache=yes
    
    - name: Ensure Nginx Start
      service:
        name: nginx
        state: started

    - name: Ensure Php Install
      apt: 
        name: ['php']
        update_cache:  yes 
        
    - name: Ensure Php-fpm Install
      apt: 
        name: ['php-fpm']
        update_cache:  yes 
    - name: Ensure Copy Nginx Configuration File
      copy: dest=/etc/nginx/sites-available/default
            src=./default

    - name: Ensure Copy Php Configuration File
      copy: dest=/var/www/html/index.php
            src=./index.php

    - name: Ensure Nginx restart
      service:
        name: nginx
        state: restarted

- hosts: haproxy
  become: yes
  vars:
    Mymessage: "Welcome to haproxy loadbalancer"
    algorithm:  roundrobin
    haproxy_host_ipv4_address: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
  tasks:
    - name: Ensure haproxy Install
      become: yes 
      apt: 
        name: haproxy 
        state:  present
    
    - name: Ensure Copy haproxy Configuration File 
      copy: dest=/etc/haproxy/haproxy.cfg
            src=./haproxy.cfg.j2
        
    - name: Ensure haproxy Restart
      service:  
        name: haproxy
        state: restarted